//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Course { get; set; }
        public string Stream { get; set; }
        public string College { get; set; }
    }
}
